<a href="https://colab.research.google.com/github/jaskiratbudhmaan-ship-it/LocalRepo/blob/main/NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([10,20,30,40])
print(arr)

[10 20 30 40]


In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr1 = np.array([[1,2,3,4],[5,6,7,8],[2,4,6,8]])
print(arr1)

[[1 2 3 4]
 [5 6 7 8]
 [2 4 6 8]]


In [ ]:
print(arr[0:3])

[10 20 30]


In [ ]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr1[0:2,0:2]

array([[1, 2],
       [5, 6]])

In [ ]:
arr1[1,2:4]

array([7, 8])

In [ ]:
arr1[2,:]

array([2, 4, 6, 8])

In [ ]:
np.shape(arr1)

(3, 4)

In [ ]:
arr1.shape

(3, 4)

In [ ]:
np.size(arr1)

12

In [ ]:
np.ndim(arr1)

2

In [ ]:
arr1.dtype

dtype('int64')

In [ ]:
a = [30,20,40,20,30],[40,20,10,40,20]
arr = np.array(a)

In [ ]:
arr.shape

(2, 5)

In [ ]:
len(arr)

2

In [ ]:
arr.size

10

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr.astype(float)

array([[30., 20., 40., 20., 30.],
       [40., 20., 10., 40., 20.]])

In [ ]:
arr1 = np.array([30,40,60,20,10])
arr2 = np.array([30,20,10,20,20])

In [ ]:
arr1+arr2

array([60, 60, 70, 40, 30])

In [ ]:
np.add(arr1,arr2)

array([60, 60, 70, 40, 30])

In [ ]:
arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,40],[20,10]])
np.add(arr1,arr2)


array([[60, 80],
       [40, 20]])

In [ ]:
np.add(arr1,arr2)

array([[60, 80],
       [40, 20]])

In [ ]:
np.subtract(arr1,arr2)

array([[0, 0],
       [0, 0]])

In [ ]:
np.multiply(arr1,arr2)

array([[ 900, 1600],
       [ 400,  100]])

In [ ]:
np.divide(arr1,arr2)

array([[1., 1.],
       [1., 1.]])

In [ ]:
arr1 = np.array([3,4,5,6])
arr2 = np.array([3])
np.power(arr1,arr2)

array([ 27,  64, 125, 216])

In [ ]:
np.sqrt(arr1)

array([1.73205081, 2.        , 2.23606798, 2.44948974])

In [ ]:
a = [30,40,50]
b = [5,5,3]
#concatenate
arr1 = np.array(a)
arr2 = np.array(b)

In [ ]:
np.concatenate([arr1,arr2])

array([30, 40, 50,  5,  5,  3])

In [ ]:
np.concatenate([arr1,arr2],axis = 1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
a = [30,40,50],[60,70,80]
b = [5,5,3],[33,5,5]
#concatenate
arr1 = np.array(a)
arr2 = np.array(b)

In [ ]:
np.concatenate([arr1,arr2],axis = 1)

array([[30, 40, 50,  5,  5,  3],
       [60, 70, 80, 33,  5,  5]])

In [ ]:
np.concatenate([arr1,arr2],axis = 0)

array([[30, 40, 50],
       [60, 70, 80],
       [ 5,  5,  3],
       [33,  5,  5]])

In [ ]:
np.hstack([arr1,arr2]) #horizontal concatenation

array([[30, 40, 50,  5,  5,  3],
       [60, 70, 80, 33,  5,  5]])

In [ ]:
np.vstack([arr1,arr2]) #vertical concatenation

array([[30, 40, 50],
       [60, 70, 80],
       [ 5,  5,  3],
       [33,  5,  5]])

In [ ]:
a = np.array([20,40,30,40,10,20])
b = np.array_split(a,3) #kisko split krna hai and kitne parts main split krna hai

In [ ]:
b[1]

array([30, 40])

In [ ]:
a = np.array([[20,40,30],[40,10,20]])

In [ ]:
np.array_split(a,4)

[array([[20, 40, 30]]),
 array([[40, 10, 20]]),
 array([], shape=(0, 3), dtype=int64),
 array([], shape=(0, 3), dtype=int64)]

In [ ]:
#Adding and removing elelments in numpy array
#np.append(h,g)--> appends items to an array
#np.insert(a,1,5)--> inserts items in an array
#np.delete(a,[1]) --> delete items from an array

In [ ]:
a = np.array([20,30,40,60])
np.append(a,90)

array([20, 30, 40, 60, 90])

In [ ]:
a = np.array([20,30,40,60])
np.append(a,[90,100])

array([ 20,  30,  40,  60,  90, 100])

In [ ]:
np.insert(a,1,50) # array , index, value

array([20, 50, 30, 40, 60])

In [ ]:
a = np.array([[20,30],[40,60]])
np.insert(a,1,[50,60],axis = 0)

array([[20, 30],
       [50, 60],
       [40, 60]])

In [ ]:
np.insert(a,[1,2],[50,60],axis = 1)

array([[20, 50, 30, 60],
       [40, 50, 60, 60]])

In [ ]:
np.delete(a,1,axis=1)

array([[20],
       [40]])

In [ ]:
#NUMPY SORT,FILTER,SEARCH
ar = np.array([[7,8,12,5,9],[2,8,5,1,3]])
np.sort(ar)

array([ 5,  7,  8,  9, 12])

In [ ]:
ar = np.array([[7,8,12,5,9],[2,8,5,1,3]]) #2d
np.sort(ar)

array([[ 5,  7,  8,  9, 12],
       [ 1,  2,  3,  5,  8]])

In [ ]:
ar = np.array([3,4,1,7,8])
s = np.where(ar == 4)
print(s)

(array([1]),)


In [ ]:
ar = np.array([3,4,1,7,8])
s = np.where(ar%2==0)
print(s)

(array([1, 4]),)


In [ ]:
#searchsorted --> gives index of the element which we seareced for , but array needs to be sorted
ar = np.array([3,4,5,6,7])
ss = np.searchsorted(ar,6)
print(ss)

3


In [ ]:
# filter
ar = np.array([20,30,40,50])
fa =[True,False,True,False]
new = ar[fa]
print(new)

[20 40]


In [ ]:
# filter second method
ar = np.array([20,30,40,50])
fa = ar>35
new = ar[fa]
print(new)

[40 50]


In [ ]:
# Aggregation finctions in numpy
np.sum()
np.max()
np.min()
np.size()
np.mean()
np.cumsum() # cummulative sum
np.cumprod() # cummulative product


In [ ]:
a = [100,150,199,200,250,130]
b = [10,50,30,40,30,10]
price = np.array(a)
quantity = np.array(b)
c = np.cumprod([price,quantity],axis = 0)
print(c)
print(np.sum(c[1]))

[[ 100  150  199  200  250  130]
 [1000 7500 5970 8000 7500 1300]]
31270


In [ ]:
# Satatistical function
a = np.array([200,300,150,130,200,280])
print(np.mean(a)) # sum of all the values divide by the numbers of values

210.0


In [ ]:
np.median(a) # data is first sorted than we take mean of central value

np.float64(200.0)

In [ ]:
import statistics as stats
stats.mode(a) #most reoccuring value

np.int64(200)

In [ ]:
np.std(a) # standard deviation

np.float64(62.1825270205921)

In [ ]:
np.var(a) # variance is square of standard deviation

np.float64(3866.6666666666665)

In [ ]:
# -1 represent inversely proportional relationship
# 1 represents proportional relationship
# 0 means no relationship
tabacco_consumption = [30,50,10,30,50,40]
deaths = [100,120,70,100,120,112]
print(np.corrcoef([tabacco_consumption,deaths]))

[[1.         0.99015454]
 [0.99015454 1.        ]]


In [ ]:
price = [300,100,350,150,200]
sales = [10,20,7,17,3]
print(np.corrcoef([price,sales]))

[[ 1.         -0.66621445]
 [-0.66621445  1.        ]]
